// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVa5YF6ks4XsCSB0SVINxphFfwXv62aio',
    appId: '1:642062146388:web:2982c530cc840da45446c1',
    messagingSenderId: '642062146388',
    projectId: 'semana-rootgoods-f939c',
    authDomain: 'semana-rootgoods-f939c.firebaseapp.com',
    databaseURL: 'https://semana-rootgoods-f939c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'semana-rootgoods-f939c.firebasestorage.app',
    measurementId: 'G-5TF46ZYETF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVMZKGFGTUY8AO8sFS-Z8aghkEcpXPick',
    appId: '1:642062146388:android:48ad6efd056cb6855446c1',
    messagingSenderId: '642062146388',
    projectId: 'semana-rootgoods-f939c',
    databaseURL: 'https://semana-rootgoods-f939c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'semana-rootgoods-f939c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4TcjdxXlAnjMw2MOaQctCqh80SL0HCnE',
    appId: '1:642062146388:ios:4533f6490936d8ac5446c1',
    messagingSenderId: '642062146388',
    projectId: 'semana-rootgoods-f939c',
    databaseURL: 'https://semana-rootgoods-f939c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'semana-rootgoods-f939c.firebasestorage.app',
    iosBundleId: 'com.example.myTfliteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4TcjdxXlAnjMw2MOaQctCqh80SL0HCnE',
    appId: '1:642062146388:ios:4533f6490936d8ac5446c1',
    messagingSenderId: '642062146388',
    projectId: 'semana-rootgoods-f939c',
    databaseURL: 'https://semana-rootgoods-f939c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'semana-rootgoods-f939c.firebasestorage.app',
    iosBundleId: 'com.example.myTfliteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVa5YF6ks4XsCSB0SVINxphFfwXv62aio',
    appId: '1:642062146388:web:d1fa851a7c44f5a15446c1',
    messagingSenderId: '642062146388',
    projectId: 'semana-rootgoods-f939c',
    authDomain: 'semana-rootgoods-f939c.firebaseapp.com',
    databaseURL: 'https://semana-rootgoods-f939c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'semana-rootgoods-f939c.firebasestorage.app',
    measurementId: 'G-3ZSD4TGZGY',
  );

}